import { execFileSync } from "node:child_process";
import { mkdtemp, mkdir, readFile, readdir, realpath, stat, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { deinitializeProject, initializeProject, ProjectRegistryStore } from "../../src/cli/commands/init";
import { removeTemporary } from "../support/temporary-root";

const roots: string[] = [];
afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => removeTemporary(root)));
});

async function gitProject(): Promise<{ root: string; project: string; home: string }> {
  const root = await mkdtemp(join(tmpdir(), "alp-clean-init-"));
  roots.push(root);
  const project = join(root, "project");
  const home = join(root, "home");
  await mkdir(project);
  await mkdir(home);
  execFileSync("git", ["init", "-q"], { cwd: project });
  await writeFile(join(project, "README.md"), "# project\n");
  execFileSync("git", ["add", "README.md"], { cwd: project });
  execFileSync("git", ["-c", "user.name=Test", "-c", "user.email=test@example.com", "commit", "-qm", "init"], { cwd: project });
  return { root, project, home };
}

describe("alp init", () => {
  it("registers the workspace outside the project and leaves git/runtime config clean", async () => {
    const { project, home } = await gitProject();
    const store = new ProjectRegistryStore({ file: join(home, ".alp", "projects.json") });
    const before = execFileSync("git", ["status", "--porcelain"], { cwd: project, encoding: "utf8" });

    await initializeProject({ project }, { store });
    await initializeProject({ project }, { store });

    expect(execFileSync("git", ["status", "--porcelain"], { cwd: project, encoding: "utf8" })).toBe(before);
    await expect(readdir(project)).resolves.toEqual([".git", "README.md"]);
    expect(JSON.parse(await readFile(join(home, ".alp", "projects.json"), "utf8"))).toEqual({
      version: 1,
      projects: [{ path: await realpath(project) }],
    });
  });

  it("installs the SessionStart hook when given a repo root, without dirtying git status", async () => {
    const { root, project, home } = await gitProject();
    const repoRoot = join(root, "alp-code");
    const store = new ProjectRegistryStore({ file: join(home, ".alp", "projects.json") });
    const before = execFileSync("git", ["status", "--porcelain"], { cwd: project, encoding: "utf8" });

    await initializeProject({ project, repoRoot }, { store });
    await initializeProject({ project, repoRoot }, { store });

    const settings = JSON.parse(await readFile(join(project, ".claude", "settings.local.json"), "utf8"));
    expect(settings.$generatedBy).toBe("alp init");
    expect(settings.hooks.SessionStart[0].hooks[0].command).toContain("session-boot.cjs");
    // The generated file is excluded per-clone, so the project stays visibly clean and the
    // exclude entry is written exactly once across repeated inits.
    expect(execFileSync("git", ["status", "--porcelain"], { cwd: project, encoding: "utf8" })).toBe(before);
    const exclude = await readFile(join(project, ".git", "info", "exclude"), "utf8");
    expect(exclude.split(/\r?\n/).filter((line) => line.trim() === ".claude/settings.local.json")).toHaveLength(1);

    await deinitializeProject({ project, repoRoot }, { store });
    await expect(stat(join(project, ".claude", "settings.local.json"))).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("deinit removes owned legacy runtime artifacts, restores backups, preserves foreign files, and is idempotent", async () => {
    const { root, project, home } = await gitProject();
    const repoRoot = join(root, "alp-code");
    const skill = join(repoRoot, "skills", "owned");
    await mkdir(skill, { recursive: true });
    await mkdir(join(project, ".claude", "skills"), { recursive: true });
    await mkdir(join(project, ".agents", "skills"), { recursive: true });
    await mkdir(join(project, ".codex"), { recursive: true });
    const claude = join(project, ".claude", "settings.local.json");
    const codex = join(project, ".codex", "config.toml");
    await writeFile(claude, '{"$generatedBy":"alp init"}\n');
    await writeFile(`${claude}.alp-backup`, '{"mine":true}\n');
    await writeFile(codex, "# generated by `alp init`\n");
    await writeFile(join(project, ".agents", "skills", "foreign.txt"), "keep\n");
    await symlink(skill, join(project, ".claude", "skills", "owned"));
    await symlink(skill, join(project, ".agents", "skills", "owned"));
    const store = new ProjectRegistryStore({ file: join(home, ".alp", "projects.json") });
    await initializeProject({ project }, { store });

    await deinitializeProject({ project, repoRoot }, { store });
    await deinitializeProject({ project, repoRoot }, { store });

    expect(await readFile(claude, "utf8")).toBe('{"mine":true}\n');
    await expect(stat(codex)).rejects.toMatchObject({ code: "ENOENT" });
    expect(await readFile(join(project, ".agents", "skills", "foreign.txt"), "utf8")).toBe("keep\n");
    await expect(stat(join(project, ".claude", "skills", "owned"))).rejects.toMatchObject({ code: "ENOENT" });
    await expect(stat(join(project, ".agents", "skills", "owned"))).rejects.toMatchObject({ code: "ENOENT" });
    expect(JSON.parse(await readFile(join(home, ".alp", "projects.json"), "utf8"))).toEqual({ version: 1, projects: [] });
  });
});
